name: waffarha_challenge
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter

  api_client:
    path: packages/api_client
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true
